// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SEBLaIQxk3A_wFniq0XZ4afZFk5PX20',
    appId: '1:427998995854:web:51a95fb94df78eb113b0df',
    messagingSenderId: '427998995854',
    projectId: 'authentication-form-70c3b',
    authDomain: 'authentication-form-70c3b.firebaseapp.com',
    storageBucket: 'authentication-form-70c3b.appspot.com',
    measurementId: 'G-BBW99TFY4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWRDnZjIIf3Rsleu3w8P_F98Q1UYqWNg',
    appId: '1:427998995854:android:5daca03ed76516f413b0df',
    messagingSenderId: '427998995854',
    projectId: 'authentication-form-70c3b',
    storageBucket: 'authentication-form-70c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAiEhK7EbCRGWpq_EEdlChReBmy_CH_s',
    appId: '1:427998995854:ios:238ad42c9e40558913b0df',
    messagingSenderId: '427998995854',
    projectId: 'authentication-form-70c3b',
    storageBucket: 'authentication-form-70c3b.appspot.com',
    iosBundleId: 'com.example.authForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqAiEhK7EbCRGWpq_EEdlChReBmy_CH_s',
    appId: '1:427998995854:ios:29d236f5387ab57013b0df',
    messagingSenderId: '427998995854',
    projectId: 'authentication-form-70c3b',
    storageBucket: 'authentication-form-70c3b.appspot.com',
    iosBundleId: 'com.example.authForm.RunnerTests',
  );
}
